trigger:
- master   # only branches go here
- main   # only branches go here

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerHubConnection: 'arunkamboj-dockerhub-conn'
  dockerHubUsername: 'arunkamboj'
  imageGateway: 'microservice-gateway'
  imageProduct: 'product-microservice'
  imageUser: 'user-microservice'

steps:
# ✅ Install Docker

- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'

# Copy repo files to server
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Arun-deployment'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/ubuntu/arunkamboj/app'
    
# Run docker-compose on server
- task: SSH@0
  displayName: 'Deploy microservices to server'
  inputs:
    sshEndpoint: 'Arun-deployment'
    runOptions: 'commands'
    commands: |
      docker pull arunkamboj/microservice-gateway:latest
      docker pull arunkamboj/user-microservice:latest
      docker pull arunkamboj/product-microservice:latest
      cd /home/ubuntu/arunkamboj/app
      docker-compose down
      docker-compose up -d --build
    readyTimeout: '20000'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'

# ✅ Build & Push Gateway Image

- task: Docker@2
  displayName: 'Build & Push Gateway Image'
  inputs:
    containerRegistry: '$(dockerHubConnection)'
    repository: '$(dockerHubUsername)/$(imageGateway)'
    command: 'buildAndPush'
    Dockerfile: 'Microservice-gateway/Dockerfile'
    buildContext: 'Microservice-gateway'
    tags: 'latest'

# ✅ Build & Push Product Microservice Image
- task: Docker@2
  displayName: 'Build & Push Product Microservice Image'
  inputs:
    containerRegistry: '$(dockerHubConnection)'
    repository: '$(dockerHubUsername)/$(imageProduct)'
    command: 'buildAndPush'
    Dockerfile: 'Product-Microservice/Dockerfile'
    buildContext: 'Product-Microservice'
    tags: 'latest'

# ✅ Build & Push User Microservice Image
- task: Docker@2
  displayName: 'Build & Push User Microservice Image'
  inputs:
    containerRegistry: '$(dockerHubConnection)'
    repository: '$(dockerHubUsername)/$(imageUser)'
    command: 'buildAndPush'
    Dockerfile: 'User-Microservice/Dockerfile'
    buildContext: 'User-Microservice'
    tags: 'latest'

# ✅ Run docker-compose for integration tests
- script: |
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    docker-compose --version
    displayName: 'Install docker-compose'
    echo "Starting services with docker-compose..."
    docker-compose -f docker-compose.yml up -d --build
    echo "Waiting for MongoDB to be ready..."
    sleep 20
    echo "Running tests..."
    docker exec microservice-gateway npm run test || true
    docker exec product-microservice npm run test || true
    docker exec user-microservice npm run test || true
    echo "Stopping services..."
    docker-compose -f docker-compose.yml down
  displayName: 'Run Integration Tests with Docker Compose'
